path:
  data: /%DATA_DIR
  logs: /var/log
cluster.name: %CLUSTER_NAME%
node.name: elasic
node.master: true
index.number_of_shards: 5
index.number_of_replicas: 0
network.bind_host: 0.0.0.0
network.host: 0.0.0.0
transport.tcp.port: 9300-9400
http.port: 9200-9300
discovery.zen.ping.timeout: 30s
discovery.zen.ping.multicast.enabled: true
discovery.zen.ping.unicast.hosts: ["127.0.0.1"]
action.disable_delete_all_indices: true
action.auto_create_index: true
bootstrap.mlockall: true
