sudo: required
group: edge

services:
  - docker

before_install:
  - docker pull alpine:3.6

install:
  - travis_retry docker build --tag bodsch/docker-elasticsearch .
  - docker run --detach --name elasticsearch bodsch/docker-elasticsearch

script:
  - docker ps | grep -q elasticsearch

before_script:
  - sysctl -w vm.max_map_count=262144
